updated taskfiles and load script logic

diff --git a/taskfiles/DockerTaskfile.yml b/taskfiles/DockerTaskfile.yml
--- a/taskfiles/DockerTaskfile.yml
+++ b/taskfiles/DockerTaskfile.yml
@@ -65,14 +65,18 @@ tasks:
       DESTINATION: '{{.DESTINATION | default ""}}'
     preconditions:
       - sh: |
-          if [ "{{.RUN_MODE}}" = "extract" ] && [ -z "{{.MAX}}" ]; then
-            echo "Error: --max must be set when RUN_MODE is 'extract'"
-            exit 1
-          fi
+          echo "{{.RUN_MODE}}"
 
-          if [ "{{.RUN_MODE}}" = "load" ] && [ -z "{{.DESTINATION}}" ]; then
-            echo "Error: --destin must be set when RUN_MODE is 'load'"
-            exit 1
+          if [ "{{.RUN_MODE}}" = "extract" ]; then
+            if [ -z "{{.MAX}}" ]; then
+              echo "Error: --max must be set when RUN_MODE is 'extract'"
+              exit 1
+            fi
+          elif [ "{{.RUN_MODE}}" = "load" ]; then
+            if [ -z "{{.DESTINATION}}" ]; then
+              echo "Error: --destin must be set when RUN_MODE is 'load'"
+              exit 1
+            fi
           fi
     cmds:
       - |
diff --git a/taskfiles/RunCLI.yml b/taskfiles/RunCLI.yml
--- a/taskfiles/RunCLI.yml
+++ b/taskfiles/RunCLI.yml
@@ -9,11 +9,21 @@ tasks:
       RUN_NAME: '{{.RUN_NAME | default "camera-photo"}}'
       RUN_MODE: '{{.RUN_MODE | default "extract"}}'
       MAX: '{{.MAX | default ""}}'
+      DESTINATION: '{{.DESTINATION | default ""}}'
     preconditions:
       - sh: |
-          if [ "{{.RUN_MODE}}" = "extract" ] && [ -z "{{.MAX}}" ]; then
-            echo "Error: --max must be set when RUN_MODE is 'extract'"
-            exit 1
+          echo "{{.RUN_MODE}}"
+
+          if [ "{{.RUN_MODE}}" = "extract" ]; then
+            if [ -z "{{.MAX}}" ]; then
+              echo "Error: --max must be set when RUN_MODE is 'extract'"
+              exit 1
+            fi
+          elif [ "{{.RUN_MODE}}" = "load" ]; then
+            if [ -z "{{.DESTINATION}}" ]; then
+              echo "Error: --destin must be set when RUN_MODE is 'load'"
+              exit 1
+            fi
           fi
     cmds:
-      - python run_script.py --run_group {{.RUN_GROUP}} --run_name {{.RUN_NAME}} --run_mode {{.RUN_MODE}} {{if eq .RUN_MODE "extract"}}--max {{.MAX}}{{end}}
+      - python run_script.py --run_group {{.RUN_GROUP}} --run_name {{.RUN_NAME}} --run_mode {{.RUN_MODE}} {{if eq .RUN_MODE "extract"}}--max {{.MAX}}{{end}} {{if eq .RUN_MODE "load"}}--destin {{.DESTINATION}}{{end}}
